name: test-build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: snapcore/action-build@v1
        id: build

      - uses: diddlesnaps/snapcraft-review-action@v1
        with:
          snap: ${{ steps.build.outputs.snap }}
          isClassic: 'true'
          # Plugs and Slots declarations to override default denial (requires store assertion to publish)
          # plugs: ./plug-declaration.json
          # slots: ./slot-declaration.json

      - name: Archive the build product
        uses: actions/upload-artifact@v3
        with:
          name: test
          path: autotools-cross-compile-example_1.0_armhf.snap

      - name: Display structure of downloaded files
        run: |
          sudo apt-get -y install debootstrap qemu-user-static squashfs-tools
          sudo debootstrap --arch=armhf jammy armhf-jammy
          unsquashfs autotools-cross-compile-example_1.0_armhf.snap
          sudo cp squashfs-root/usr/bin/* armhf-jammy/root/
          sudo chroot armhf-jammy /root/autotools-cross-compile-example
